version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    depends_on:
      - db
      - redis
      - mailer
    networks:
      - db
      - redis
      - mailer
    ports:
      - "5150:5150"
    volumes:
      - ./:/usr/src/seco
      - cargo-cache:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - target-cache:/usr/src/seco/target
    env_file:
      - .env
    tty: true
    command: >
      watchexec
      -r
      -i target -i target/** -i .git -i '.git/**'
      -i /usr/local/cargo -i /usr/local/cargo/** -i cargo-cache -i cargo-git
      -i '**/*.swp' -i '**/*~' -i '**/.#*'
      -w src -w Cargo.toml
      -- cargo loco start --server-and-worker -b 0.0.0.0
#    command: cargo loco start --server-and-worker -b 0.0.0.0

  db:
    image: postgres:17.4-bookworm
    restart: unless-stopped
    ports:
      - "5433:5432"
    networks:
      - db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - redis
  mailer:
    image: mailtutan/mailtutan:latest
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - mailer

volumes:
  postgres-data: {}
  cargo-cache:
  cargo-git:
  target-cache:


networks:
  db:
  redis:
  mailer: