//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "delivery_method_services")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub active: bool,
    pub delivery_method_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::delivery_methods::Entity",
        from = "Column::DeliveryMethodId",
        to = "super::delivery_methods::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DeliveryMethods,
}

impl Related<super::delivery_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeliveryMethods.def()
    }
}
