//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::OrderStatusEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub order_number: String,
    pub final_price: Decimal,
    #[sea_orm(column_type = "Text", nullable)]
    pub delivery_address_detail: Option<String>,
    pub payment_method_detail: Option<Json>,
    pub status: OrderStatusEnum,
    pub buyer_id: i32,
    pub delivery_address_id: i32,
    pub payment_method_id: i32,
    pub delivery_method_service_id: i32,
    pub delivery_method_service_price: Decimal,
    pub delivery_method_service_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::delivery_addresses::Entity",
        from = "Column::DeliveryAddressId",
        to = "super::delivery_addresses::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DeliveryAddresses,
    #[sea_orm(has_many = "super::order_items::Entity")]
    OrderItems,
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PaymentMethods,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::BuyerId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::delivery_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeliveryAddresses.def()
    }
}

impl Related<super::order_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItems.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
