//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::product_images::Entity as ProductImages;
// pub use crate::models::products::Entity as ProductImages;
pub use super::products::Entity as Products;
pub use super::users::Entity as Users;
