//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize, ToSchema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "action_type")]
pub enum ActionType {
    #[sea_orm(string_value = "CounterOffer")]
    CounterOffer,
    #[sea_orm(string_value = "Accept")]
    Accept,
    #[sea_orm(string_value = "Decline")]
    Decline,
    #[sea_orm(string_value = "Offer")]
    Offer,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize, ToSchema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "condition")]
pub enum Condition {
    #[sea_orm(string_value = "BrandNew")]
    BrandNew,
    #[sea_orm(string_value = "MintCondition")]
    MintCondition,
    #[sea_orm(string_value = "LikeNew")]
    LikeNew,
    #[sea_orm(string_value = "Excellent")]
    Excellent,
    #[sea_orm(string_value = "Good")]
    Good,
    #[sea_orm(string_value = "Fair")]
    Fair,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize, ToSchema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "offering_status")]
pub enum OfferingStatus {
    #[sea_orm(string_value = "InProgress")]
    InProgress,
    #[sea_orm(string_value = "Accepted")]
    Accepted,
    #[sea_orm(string_value = "Declined")]
    Declined,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize, ToSchema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "order_status_enum")]
pub enum OrderStatusEnum {
    #[sea_orm(string_value = "AwaitingPayment")]
    AwaitingPayment,
    #[sea_orm(string_value = "AwaitingFulfillment")]
    AwaitingFulfillment,
    #[sea_orm(string_value = "AwaitingShipment")]
    AwaitingShipment,
    #[sea_orm(string_value = "Shipped")]
    Shipped,
    #[sea_orm(string_value = "Completed")]
    Completed,
    #[sea_orm(string_value = "Returned")]
    Returned,
    #[sea_orm(string_value = "Cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize, ToSchema)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "payment_method_gateway_enum"
)]
pub enum PaymentMethodGatewayEnum {
    #[sea_orm(string_value = "Xendit")]
    Xendit,
    #[sea_orm(string_value = "Tripay")]
    Tripay,
    #[sea_orm(string_value = "Midtrans")]
    Midtrans,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize, ToSchema)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "payment_method_name_enum"
)]
pub enum PaymentMethodNameEnum {
    #[sea_orm(string_value = "COD")]
    COD,
    #[sea_orm(string_value = "QRIS")]
    QRIS,
    #[sea_orm(string_value = "VirtualAccount")]
    VirtualAccount,
    #[sea_orm(string_value = "BankTransfer")]
    BankTransfer,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize, ToSchema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "product_status")]
pub enum ProductStatus {
    #[sea_orm(string_value = "Draft")]
    Draft,
    #[sea_orm(string_value = "Active")]
    Active,
    #[sea_orm(string_value = "Sold")]
    Sold,
}
