//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use utoipa::ToSchema;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize, ToSchema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "action_type")]
pub enum ActionType {
    #[sea_orm(string_value = "CounterOffer")]
    CounterOffer,
    #[sea_orm(string_value = "Accept")]
    Accept,
    #[sea_orm(string_value = "Decline")]
    Decline,
    #[sea_orm(string_value = "Offer")]
    Offer,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize, ToSchema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "condition")]
pub enum Condition {
    #[sea_orm(string_value = "BrandNew")]
    BrandNew,
    #[sea_orm(string_value = "MintCondition")]
    MintCondition,
    #[sea_orm(string_value = "LikeNew")]
    LikeNew,
    #[sea_orm(string_value = "Excellent")]
    Excellent,
    #[sea_orm(string_value = "Good")]
    Good,
    #[sea_orm(string_value = "Fair")]
    Fair,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize, ToSchema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "offering_status")]
pub enum OfferingStatus {
    #[sea_orm(string_value = "InProgress")]
    InProgress,
    #[sea_orm(string_value = "Accepted")]
    Accepted,
    #[sea_orm(string_value = "Declined")]
    Declined,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize, ToSchema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "product_status")]
pub enum ProductStatus {
    #[sea_orm(string_value = "Draft")]
    Draft,
    #[sea_orm(string_value = "Active")]
    Active,
    #[sea_orm(string_value = "Sold")]
    Sold,
}
